In [40]:
import pandas as pd

mun = pd.read_csv("data/aux_municipio.csv", delimiter=";",dtype=str,encoding="latin1")

mun.head()

,uf_sigla,uf_des,meso,meso_des,micro,micro_des,mun_cod_ibge,mun_cod,mun_des
0,11,Rondônia,02,Leste Rondoniense,006,Cacoal,00015,1100015,Alta Floresta D'Oeste
1,11,Rondônia,02,Leste Rondoniense,006,Cacoal,00379,1100379,Alto Alegre dos Parecis
2,11,Rondônia,02,Leste Rondoniense,003,Ariquemes,00403,1100403,Alto Paraíso
3,11,Rondônia,02,Leste Rondoniense,005,Alvorada D'Oeste,00346,1100346,Alvorada D'Oeste
4,11,Rondônia,02,Leste Rondoniense,003,Ariquemes,00023,1100023,Ariquemes

In [46]:
mun_tse = pd.read_csv("data/aux_mun_tse_code.csv", delimiter=";", dtype=str,encoding="latin1")


mun_tse.groupby("Ano").count()
#mun_tse.set_index("IBGEcod").join(mun.set_index("mun_cod"))
mun_tse.head()

    Ano SiglaUF TSEcod  IBGEcod     Municipio
0  1994      AC   1120  1200013    ACRELANDIA
1  1994      AC   1570  1200054  ASSIS BRASIL
2  1994      AC   1058  1200104     BRASILEIA
3  1994      AC   1007  1200138        BUJARI
4  1994      AC   1015  1200179      CAPIXABA

###

In [47]:
mun_ano = mun_tse.groupby(["SiglaUF","IBGEcod","TSEcod"],as_index=False).max()
mun_ano = mun_ano.drop(["Ano"],1)

In [43]:
mun_ano.head()

  SiglaUF  IBGEcod TSEcod     Municipio
0      AC  1200013   1120    ACRELANDIA
1      AC  1200054   1570  ASSIS BRASIL
2      AC  1200104   1058     BRASILEIA
3      AC  1200138   1007        BUJARI
4      AC  1200179   1015      CAPIXABA

### Juntando as duas tabelas

In [48]:
mun_ano["CODIGO_IBGE"] = mun_ano["IBGEcod"]

mun_ano_tse_cod = mun_ano.set_index("IBGEcod").join(mun.set_index("mun_cod"))
mun_ano_tse_cod.head()

,SiglaUF,TSEcod,Municipio,CODIGO_IBGE,uf_sigla,uf_des,meso,meso_des,micro,micro_des,mun_cod_ibge,mun_des
1100015,RO,310,ALTA FLORESTA D OESTE,1100015,11,Rondônia,02,Leste Rondoniense,006,Cacoal,00015,Alta Floresta D'Oeste
1100023,RO,78,ARIQUEMES,1100023,11,Rondônia,02,Leste Rondoniense,003,Ariquemes,00023,Ariquemes
1100031,RO,450,CABIXI,1100031,11,Rondônia,02,Leste Rondoniense,008,Colorado do Oeste,00031,Cabixi
1100049,RO,94,CACOAL,1100049,11,Rondônia,02,Leste Rondoniense,006,Cacoal,00049,Cacoal
1100056,RO,272,CEREJEIRAS,1100056,11,Rondônia,02,Leste Rondoniense,008,Colorado do Oeste,00056,Cerejeiras

0       1200013
1       1200054
2       1200104
3       1200138
4       1200179
5       1200203
6       1200252
7       1200302
8       1200328
9       1200336
10      1200344
11      1200351
12      1200385
13      1200393
14      1200401
15      1200427
16      1200435
17      1200450
18      1200500
19      1200609
20      1200708
21      1200807
22      2700102
23      2700201
24      2700300
25      2700409
26      2700508
27      2700607
28      2700706
29      2700805
         ...
5537    1718659
5538    1718709
5539    1718758
5540    1718808
5541    1718840
5542    1718865
5543    1718881
5544    1718899
5545    1718907
5546    1719004
5547    1720002
5548    1720101
5549    1720150
5550    1720200
5551    1720259
5552    1720309
5553    1720499
5554    1720655
5555    1720804
5556    1720853
5557    1720903
5558    1720937
5559    1720978
5560    1721000
5561    1721109
5562    1721208
5563    1721257
5564    1721307
5565    1722081
5566    1722107
Name: IBGEcod, Length: 5567, dtype: object

In [49]:
mun_ano_tse_cod = mun_ano_tse_cod.sort_values('TSEcod')

In [50]:
mun_ano_tse_cod.head()

,SiglaUF,TSEcod,Municipio,CODIGO_IBGE,uf_sigla,uf_des,meso,meso_des,micro,micro_des,mun_cod_ibge,mun_des
2201960,PI,10006,BRASILEIRA,2201960,22,Piauí,01,Norte Piauiense,001,Baixo Parnaíba Piauiense,01960,Brasileira
2200103,PI,10014,AGRICOLANDIA,2200103,22,Piauí,02,Centro-Norte Piauiense,005,Médio Parnaíba Piauiense,00103,Agricolândia
2200277,PI,10022,ALEGRETE DO PIAUI,2200277,22,Piauí,04,Sudeste Piauiense,014,Pio IX,00277,Alegrete do Piauí
2200202,PI,10030,AGUA BRANCA,2200202,22,Piauí,02,Centro-Norte Piauiense,005,Médio Parnaíba Piauiense,00202,Água Branca
2201150,PI,10049,BAIXA GRANDE DO RIBEIRO,2201150,22,Piauí,03,Sudoeste Piauiense,007,Alto Parnaíba Piauiense,01150,Baixa Grande do Ribeiro

### Teste agregações micro e meso

In [35]:
mun_ano_tse_cod.groupby(["meso","micro"])["TSEcod"].apply(list).head()

meso  micro
01    001      [00035, 00434, 00779, 00671, 00477, 00680, 004...
      002      [00213, 00019, 00795, 01139, 01104, 01473, 024...
      003      [04090, 05177, 73008, 92371, 96997, 92002, 732...
      004      [92398, 73474, 93238, 93475, 96830, 93653, 733...
      005      [96954, 92134, 92738, 73300, 73555, 96679, 938...
Name: TSEcod, dtype: object

### Adicionando ao código TSE zeros a esquerda até ter 5 digitos

In [51]:
mun_ano_tse_cod["TSEcod"] = mun_ano_tse_cod["TSEcod"].apply(lambda x: '{0:0>5}'.format(x))
mun_ano_tse_cod.head()

,SiglaUF,TSEcod,Municipio,CODIGO_IBGE,uf_sigla,uf_des,meso,meso_des,micro,micro_des,mun_cod_ibge,mun_des
2201960,PI,10006,BRASILEIRA,2201960,22,Piauí,01,Norte Piauiense,001,Baixo Parnaíba Piauiense,01960,Brasileira
2200103,PI,10014,AGRICOLANDIA,2200103,22,Piauí,02,Centro-Norte Piauiense,005,Médio Parnaíba Piauiense,00103,Agricolândia
2200277,PI,10022,ALEGRETE DO PIAUI,2200277,22,Piauí,04,Sudeste Piauiense,014,Pio IX,00277,Alegrete do Piauí
2200202,PI,10030,AGUA BRANCA,2200202,22,Piauí,02,Centro-Norte Piauiense,005,Médio Parnaíba Piauiense,00202,Água Branca
2201150,PI,10049,BAIXA GRANDE DO RIBEIRO,2201150,22,Piauí,03,Sudoeste Piauiense,007,Alto Parnaíba Piauiense,01150,Baixa Grande do Ribeiro

### Inserir dados de macro

In [23]:
a = mun_ano_tse_cod.groupby(["CODIGO_MACRO","NOME_MACRO","SIGLA_LEGENDA","NOME_LEGENDA"],as_index=False)["QTDE_VOTOS"].sum()
a.sort_values('uf_sigla').head()

KeyError: 'CODIGO_MACRO'

In [52]:
macro_uf = pd.read_csv("data/macro_uf.csv")
macro_uf.set_index("sigla_UF")

          macro         macro_des
sigla_UF
AC            1             Norte
AM            1             Norte
AP            1             Norte
PA            1             Norte
RO            1             Norte
RR            1             Norte
TO            1             Norte
AL            2          Nordeste
BA            2          Nordeste
CE            2          Nordeste
MA            2          Nordeste
PB            2          Nordeste
PE            2          Nordeste
PI            2          Nordeste
RN            2          Nordeste
SE            2          Nordeste
ES            3           Sudeste
MG            3           Sudeste
RJ            3           Sudeste
SP            3           Sudeste
PR            4               Sul
RS            4               Sul
SC            4               Sul
DF            5  Distrito Federal
GO            5      Centro-Oeste
MS            5      Centro-Oeste
MT            5      Centro-Oeste

### Adicionando colunas macro na tabela de municipio

In [53]:
mun_ano_tse_cod = mun_ano_tse_cod.set_index("SiglaUF").join(macro_uf.set_index("sigla_UF"))

In [54]:
mun_ano_tse_cod["mun_cod_ibge"] = mun_ano_tse_cod["mun_cod_ibge"].apply(lambda x: '{0:0>5}'.format(x))
mun_ano_tse_cod.head()

,TSEcod,Municipio,CODIGO_IBGE,uf_sigla,uf_des,meso,meso_des,micro,micro_des,mun_cod_ibge,mun_des,macro,macro_des
AC,01007,BUJARI,1200138,12,Acre,02,Vale do Acre,004,Rio Branco,00138,Bujari,1,Norte
AC,01015,CAPIXABA,1200179,12,Acre,02,Vale do Acre,004,Rio Branco,00179,Capixaba,1,Norte
AC,01023,PORTO ACRE,1200807,12,Acre,02,Vale do Acre,004,Rio Branco,00807,Porto Acre,1,Norte
AC,01031,SANTA ROSA DO PURUS,1200435,12,Acre,02,Vale do Acre,003,Sena Madureira,00435,Santa Rosa do Purus,1,Norte
AC,01040,MARECHAL TAUMATURGO,1200351,12,Acre,01,Vale do Juruá,001,Cruzeiro do Sul,00351,Marechal Thaumaturgo,1,Norte

### Salvando em csv os dados tratados

In [58]:
mun_ano_tse_cod = mun_ano_tse_cod.drop(["mun_cod_ibge"],1)

In [59]:
pd.set_option('precision', 0)
mun_ano_tse_cod.head()
mun_ano_tse_cod.to_csv("data/aux_mun_code.csv",header=True, index=True, encoding='utf-8')

### Sql Para criar a tabela aux_municipio no Bando de dados:
```mysql
create table aux_municipio(
UF STRING,
CODIGO_MUNICIPIO STRING,
CODIGO_IBGE STRING,
NOME_UF STRING,
CODIGO_MESO STRING,
NOME_MESO STRING,
CODIGO_MICRO STRING,
NOME_MICRO STRING,
NOME_MUNICIPIO STRING,
CODIGO_MACRO STRING,
NOME_MACRO STRING)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
'separatorChar' = '\,',
'quoteChar'     = '\"'
)
STORED AS TEXTFILE;


Alter table aux_municipio set location "s3://datascience2016/data/gzip/aux/aux_mun_code.csv.gz"
```

In [1]:
import pandas as pd

In [21]:
csv = pd.read_csv("data/aux_mun_code5570.csv", sep=";")
names = [
    "uf_sigla",
    "Cod_TSE",
    "Cod_IBGE",
    "uf_des",
    "Meso_Cod",
    "Meso_Des",
    "Micro_cod",
    "Micro_Des",
    "mun_des",
    "macro_cod",
    "macro_des"
]

In [22]:
csv

,UF_Cod,uf_sigla,Cod_TSE,Cod_IBGE,uf_des,Meso_Cod,Meso_Des,Micro_cod,Micro_Des,mun_des,macro_cod,macro_des
0,11,RO,452,1100452,Rondônia,1,Madeira-Guaporé,1,Porto Velho,Buritis,1,Norte
1,11,RO,700,1100700,Rondônia,1,Madeira-Guaporé,1,Porto Velho,Campo Novo de Rondônia,1,Norte
2,11,RO,809,1100809,Rondônia,1,Madeira-Guaporé,1,Porto Velho,Candeias do Jamari,1,Norte
3,11,RO,940,1100940,Rondônia,1,Madeira-Guaporé,1,Porto Velho,Cujubim,1,Norte
4,11,RO,1104,1101104,Rondônia,1,Madeira-Guaporé,1,Porto Velho,Itapuã do Oeste,1,Norte
5,11,RO,338,1100338,Rondônia,1,Madeira-Guaporé,1,Porto Velho,Nova Mamoré,1,Norte
6,11,RO,205,1100205,Rondônia,1,Madeira-Guaporé,1,Porto Velho,Porto Velho,1,Norte
7,11,RO,80,1100080,Rondônia,1,Madeira-Guaporé,2,Guajará-Mirim,Costa Marques,1,Norte
8,11,RO,106,1100106,Rondônia,1,Madeira-Guaporé,2,Guajará-Mirim,Guajará-Mirim,1,Norte
9,11,RO,1492,1101492,Rondônia,1,Madeira-Guaporé,2,Guajará-Mirim,São Francisco do Guaporé,1,Norte
10,11,RO,403,1100403,Rondônia,2,Leste Rondoniense,3,Ariquemes,Alto Paraíso,1,Norte
11,11,RO,23,1100023,Rondônia,2,Leste Rondoniense,3,Ariquemes,Ariquemes,1,Norte
12,11,RO,601,1100601,Rondônia,2,Leste Rondoniense,3,Ariquemes,Cacaulândia,1,Norte
13,11,RO,130,1100130,Rondônia,2,Leste Rondoniense,3,Ariquemes,Machadinho D'Oeste,1,Norte
14,11,RO,1401,1101401,Rondônia,2,Leste Rondoniense,3,Ariquemes,Monte Negro,1,Norte
15,11,RO,262,1100262,Rondônia,2,Leste Rondoniense,3,Ariquemes,Rio Crespo,1,Norte
16,11,RO,1757,1101757,Rondônia,2,Leste Rondoniense,3,Ariquemes,Vale do Anari,1,Norte
17,11,RO,1005,1101005,Rondônia,2,Leste Rondoniense,4,Ji-Paraná,Governador Jorge Teixeira,1,Norte
18,11,RO,114,1100114,Rondônia,2,Leste Rondoniense,4,Ji-Paraná,Jaru,1,Norte
19,11,RO,122,1100122,Rondônia,2,Leste Rondoniense,4,Ji-Paraná,Ji-Paraná,1,Norte
20,11,RO,1302,1101302,Rondônia,2,Leste Rondoniense,4,Ji-Paraná,Mirante da Serra,1,Norte
21,11,RO,1435,1101435,Rondônia,2,Leste Rondoniense,4,Ji-Paraná,Nova União,1,Norte
22,11,RO,155,1100155,Rondônia,2,Leste Rondoniense,4,Ji-Paraná,Ouro Preto do Oeste,1,Norte
23,11,RO,254,1100254,Rondônia,2,Leste Rondoniense,4,Ji-Paraná,Presidente Médici,1,Norte
24,11,RO,1559,1101559,Rondônia,2,Leste Rondoniense,4,Ji-Paraná,Teixeirópolis,1,Norte
25,11,RO,1609,1101609,Rondônia,2,Leste Rondoniense,4,Ji-Paraná,Theobroma,1,Norte
26,11,RO,1708,1101708,Rondônia,2,Leste Rondoniense,4,Ji-Paraná,Urupá,1,Norte
27,11,RO,1807,1101807,Rondônia,2,Leste Rondoniense,4,Ji-Paraná,Vale do Paraíso,1,Norte
28,11,RO,346,1100346,Rondônia,2,Leste Rondoniense,5,Alvorada D'Oeste,Alvorada D'Oeste,1,Norte
29,11,RO,148,1100148,Rondônia,2,Leste Rondoniense,5,Alvorada D'Oeste,Nova Brasilândia D'Oeste,1,Norte
...,...,...,...,...,...,...,...,...,...,...,...,...
5540,52,GO,8152,5208152,Goiás,5,Sul Goiano,16,Pires do Rio,Gameleira de Goiás,5,Centro-Oeste
5541,52,GO,15306,5215306,Goiás,5,Sul Goiano,16,Pires do Rio,Orizona,5,Centro-Oeste
5542,52,GO,15801,5215801,Goiás,5,Sul Goiano,16,Pires do Rio,Palmelo,5,Centro-Oeste
5543,52,GO,17401,5217401,Goiás,5,Sul Goiano,16,Pires do Rio,Pires do Rio,5,Centro-Oeste
5544,52,GO,19209,5219209,Goiás,5,Sul Goiano,16,Pires do Rio,Santa Cruz de Goiás,5,Centro-Oeste
5545,52,GO,20264,5220264,Goiás,5,Sul Goiano,16,Pires do Rio,São Miguel do Passa Quatro,5,Centro-Oeste
5546,52,GO,20603,5220603,Goiás,5,Sul Goiano,16,Pires do Rio,Silvânia,5,Centro-Oeste
5547,52,GO,21809,5221809,Goiás,5,Sul Goiano,16,Pires do Rio,Urutaí,5,Centro-Oeste
5548,52,GO,22005,5222005,Goiás,5,Sul Goiano,16,Pires do Rio,Vianópolis,5,Centro-Oeste
5549,52,GO,1207,5201207,Goiás,5,Sul Goiano,17,Catalão,Anhanguera,5,Centro-Oeste
5550,52,GO,4805,5204805,Goiás,5,Sul Goiano,17,Catalão,Campo Alegre de Goiás,5,Centro-Oeste
5551,52,GO,5109,5205109,Goiás,5,Sul Goiano,17,Catalão,Catalão,5,Centro-Oeste
5552,52,GO,5901,5205901,Goiás,5,Sul Goiano,17,Catalão,Corumbaíba,5,Centro-Oeste
5553,52,GO,6602,5206602,Goiás,5,Sul Goiano,17,Catalão,Cumari,5,Centro-Oeste
5554,52,GO,6909,5206909,Goiás,5,Sul Goiano,17,Catalão,Davinópolis,5,Centro-Oeste
5555,52,GO,8509,5208509,Goiás,5,Sul Goiano,17,Catalão,Goiandira,5,Centro-Oeste
5556,52,GO,10109,5210109,Goiás,5,Sul Goiano,17,Catalão,Ipameri,5,Centro-Oeste
5557,52,GO,14804,5214804,Goiás,5,Sul Goiano,17,Catalão,Nova Aurora,5,Centro-Oeste
5558,52,GO,15504,5215504,Goiás,5,Sul Goiano,17,Catalão,Ouvidor,5,Centro-Oeste
5559,52,GO,21304,5221304,Goiás,5,Sul Goiano,17,Catalão,Três Ranchos,5,Centro-Oeste
5560,52,GO,4102,5204102,Goiás,5,Sul Goiano,18,Quirinópolis,Cachoeira Alta,5,Centro-Oeste
5561,52,GO,4300,5204300,Goiás,5,Sul Goiano,18,Quirinópolis,Caçu,5,Centro-Oeste
5562,52,GO,9150,5209150,Goiás,5,Sul Goiano,18,Quirinópolis,Gouvelândia,5,Centro-Oeste
5563,52,GO,10802,5210802,Goiás,5,Sul Goiano,18,Quirinópolis,Itajá,5,Centro-Oeste
5564,52,GO,11305,5211305,Goiás,5,Sul Goiano,18,Quirinópolis,Itarumã,5,Centro-Oeste
5565,52,GO,12253,5212253,Goiás,5,Sul Goiano,18,Quirinópolis,Lagoa Santa,5,Centro-Oeste
5566,52,GO,16304,5216304,Goiás,5,Sul Goiano,18,Quirinópolis,Paranaiguara,5,Centro-Oeste
5567,52,GO,18508,5218508,Goiás,5,Sul Goiano,18,Quirinópolis,Quirinópolis,5,Centro-Oeste
5568,52,GO,20405,5220405,Goiás,5,Sul Goiano,18,Quirinópolis,São Simão,5,Centro-Oeste
5569,53,DF,108,5300108,Distrito Federal,1,Distrito Federal,1,Brasília,Brasília,5,Centro-Oeste

In [15]:
csv["Cod_TSE"] = csv["Cod_TSE"].apply(lambda x: '{0:0>5}'.format(x))

In [20]:
csv.to_csv("data/aux_mun_code.csv",sep=",",header=False, index=False, encoding='utf-8')

In [13]:
import pandas as pd
data = pd.read_csv("data/aux_mun_code5570.txt" , sep=";")

In [14]:
data.head()

,uf_sigla,Cod_TSE_5,Cod_IBGE,uf_des,Meso_Cod,Meso_Des,Micro_cod,Micro_Des,NOME DO MUNICÍPIO,macro_cod,macro_des
0,RR,3000,1400233,Roraima,2,Sul de Roraima,4,Sudeste de Roraima,Caroebe,1,Norte
1,RR,3026,1400282,Roraima,2,Sul de Roraima,3,Caracaraí,Iracema,1,Norte
2,RR,3093,1400308,Roraima,2,Sul de Roraima,3,Caracaraí,Mucajaí,1,Norte
3,RR,3115,1400407,Roraima,1,Norte de Roraima,2,Nordeste de Roraima,Normandia,1,Norte
4,RR,3123,1400456,Roraima,1,Norte de Roraima,1,Boa Vista,Pacaraima,1,Norte